const Images = {
    photo1: require('./images/img-1.jpg'),
    photo2: require('./images/img-2.jpg'),
    photo3: require('./images/img-3.jpg'),
    photo4: require('./images/img-4.jpg'),
    photo5: require('./images/img-5.jpg'),
    photo6: require('./images/img-6.jpg'),
    photo7: require('./images/img-7.jpg'),
    photo8: require('./images/img-8.jpg'),
    photo9: require('./images/img-9.jpg'),
    photo10: require('./images/img-10.jpg'),
    photo11: require('./images/img-11.jpg'),
    photo12: require('./images/img-12.jpg'),
    photo13: require('./images/img-13.jpg'),
    photo14: require('./images/img-14.jpg'),
    photo15: require('./images/img-15.jpg'),
    photo16: require('./images/img-16.jpg'),
    photo17: require('./images/img-17.jpg'),
    photo18: require('./images/img-18.jpg'),
    photo19: require('./images/img-19.jpg'),
    photo20: require('./images/img-20.jpg'),
    photo21: require('./images/img-21.jpg'),
    photo22: require('./images/img-22.jpg'),
    photo23: require('./images/img-23.jpg'),
    photo24: require('./images/img-24.jpg'),
    photo25: require('./images/img-25.jpg'),
    photo26: require('./images/img-26.jpg'),
    photo27: require('./images/img-27.jpg'),
    photo28: require('./images/img-28.jpg'),
    photo29: require('./images/img-29.jpg'),
    photo30: require('./images/img-30.jpg'),
    photo31: require('./images/img-31.jpg')
}

export default Images;